(define (problem rubik4)
    (:domain rubik)
    (:objects r w b g o y - color)
    (:init
        (face1 w r b)
        (face2 y g w)
        (face3 b r y)
        (face4 o b w)
        (face5 g o y)
        (face6 b r w)
        (face7 w g o)
        (face8 r y g)
    )
    (:goal (and
        (face1 w r b)
        (face2 w o b)
        (face3 y r b)
        (face4 y o b)
        (face5 w r g)
        (face6 w o g)
        (face7 y r g)
        (face8 y o g)
        )
    )
)
